services:
  runner:
    image: ghcr.io/backtik-ch/self-hosted-runner:main
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GID:-998}"
    user: root
